### ISSUE TITLE
如果分片上传的时候用Blob的话，没有name属性，上传直接报错崩溃

### ISSUE THREAD

**Issue by AliasT** [Wangsu-Cloud-Storage/wcs-js-sdk#2]
[https://github.com/Wangsu-Cloud-Storage/wcs-js-sdk/blob/master/src/uploadChunk.js#L104](https://github.com/Wangsu-Cloud-Storage/wcs-js-sdk/blob/master/src/uploadChunk.js#L104)

**Comment by Wangsu-Cloud-Storage** [comment]
name属性确实是冗余的，我们是通过token或表单传递文件名，已经删掉这个属性了。感谢反馈
